language: go
go:
  - 1.7

install:
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - swagger version
  - go get github.com/go-openapi/strfmt
  - go get github.com/go-openapi/runtime
  - go get github.com/go-openapi/errors
  - npm install newman --global

# split the tests for better time measure and fold output at the travis ui
script:
  - make gen
  - make install
  - make build
  - ./cmd/wiredcraft-test-backend-server/wiredcraft-test-backend-server --help
  - make test
  - make test-api
